### ISSUE TITLE
Information about the calibration procedure mentioned in the paper

### ISSUE THREAD

**Issue by gabrielecaddeo** [facebookresearch/MidasTouch#1]
Hi all,
Thanks for sharing with us your great work.

I read the paper and in the appendix you mentioned a necessary calibration step to be performed (I attach here the screen).

![calibration](https://user-images.githubusercontent.com/49904924/198086686-11d9d9c9-6639-4ac6-a78f-6f929ce85907.png)

However, I could not find any part of the code where you actually perform such calibration. I also saw that your renderer is designed to load a different background image given an id from the user, however this seems to require the following method from the `tacto` class that I could not find in the associated python package. https://github.com/facebookresearch/MidasTouch/blob/8e67453b1f7a9d7d9092f1c02521838539cf40af/midastouch/render/digit_renderer.py#L49 Can I have more information?

Thanks,
Gabriele

**Comment by suddhu** [comment]
Hi Gabiele! Thank you for reaching out. 

- The calibration step here is generating the training data for the TDN in TACTO, but using an assortment of background images. You can think about it as a form of data augmentation to generalize to a wider range of DIGIT sensors. I currently haven't added the data generation scripts for the TDN, but I can work on getting that open-sourced as soon as possible. Would that be of interest to you?  
- `get_background_image_path` is a function in our modified tacto repository that the conda env should automatically install.  You can find it referenced [here](https://github.com/suddhu/tacto/blob/634c37b07c025ec13093d89abe4b89ccd6c477ec/tacto/__init__.py).

**Comment by gabrielecaddeo** [comment]
Thanks for the fast reply!
> Would that be of interest to you?
>
Yes, for sure!
> You can find it referenced [here](https://github.com/suddhu/tacto/blob/634c37b07c025ec13093d89abe4b89ccd6c477ec/tacto/__init__.py).
>
Thanks for the clarification

**Comment by suddhu** [comment]
Hi @gabrielecaddeo! The data generation scripts are now live in `midastouch/data_gen` from the recent commit 13f0887f1676b6a1d03e7e7bbdee8c36c11bbe9e. Let me know if you have any further questions, and thank you for expressing interest in it! 

I'll close this issue for now, but can re-open if you would like to follow-up.
