### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by xEnVrE** [facebookresearch/MidasTouch#2]
Hi there,

shouldn't this line

https://github.com/facebookresearch/MidasTouch/blob/8e67453b1f7a9d7d9092f1c02521838539cf40af/README.md?plain=1#L112

be

```console
python midastouch/filter/live_demo.py expt.obj_model=025_mug 
```
instead?

Thanks

**Comment by suddhu** [comment]
Hi @xEnVrE! 

Thank you very much for catching that, I've fixed it in [8d67aa8](https://github.com/facebookresearch/MidasTouch/commit/8d67aa8e776bc4a1a7551b48feca8c33f15c1aad).  Appreciate it!
